site_name: TelePortraitLens document
site_description: TelePortraitLens document
site_url: https://skknyuki.github.io/TelePortraitLens/

theme:
  name: material
  features:
    - navigation.expand
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - はじまり: index.md
  - インストール:
      - 導入方法: install.md
      - 撮影クオリティ: optional1.md
  - 使用方法: howtouse.md
  - メニュー: 
      - Top: menu/menu.md
      - Lens: menu/Lens.md
      - Preset: menu/Preset.md
      - Drone: menu/Drone.md
      - Setting: menu/Setting.md
  - よくある質問: faq.md
  - 更新履歴: history.md