site_name: TelePortraitLens
site_description: VRChat avatar camera gimmick for portrait photography
site_url: https://skknyuki.github.io/TelePortraitLens/

theme:
  name: material
  features:
    - navigation.expand
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - はじまり: index.md
  - インストール:
      - 導入方法: install.md
      - 撮影クオリティ: optional1.md
  - 基本の撮影: howtouse1.md
  - 特殊な撮影: howtouse2.md
  - メニュー: 
      - Top: menu/menu.md
      - Preset: menu/Preset.md
      - P: menu/P.md
      - M: menu/M.md
      - Drone: menu/Drone.md
      - Setting: menu/Setting.md
  - よくある質問: faq.md
  - 更新履歴: history.md
  - Booth販売ページ: https://goat-cannery.booth.pm/items/8378645